FROM openjdk:latest

MAINTAINER Arne Schubert <atd.schubert@gmail.com>

ARG OSMOSIS_URL="https://bretth.dev.openstreetmap.org/osmosis-build/osmosis-0.47.tgz"
ENV OSMOSIS_URL $OSMOSIS_URL
ENV DB_HOST localhost
ENV DB_USER ianaz
ENV DB_PASSWORD any
ENV DB_NAME db-osm

RUN set -x \
  && useradd -ms /bin/bash osmosis \
  && mkdir -p /opt/osmosis \
  && curl $OSMOSIS_URL | tar xz -C /opt/osmosis \
  && ln -s /opt/osmosis/bin/osmosis /usr/local/bin/osmosis

USER osmosis
ENTRYPOINT ["sh", "-c", "osmosis --read-pbf osm.pbf --write-pgsql ${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} database=${DB_NAME} host=${DB_HOST}"]